package Principal;

/**
 *
 * @author nicol
 */
public class Principal extends javax.swing.JFrame 
{

    /**
     * Creates new form Principal
     */
    public Principal() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnProcurarA = new javax.swing.JButton();
        btnIncluirA = new javax.swing.JButton();
        btnAlterarA = new javax.swing.JButton();
        btnExcluirA = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnProcurarV = new javax.swing.JButton();
        btnIncluirV = new javax.swing.JButton();
        btnAlterarV = new javax.swing.JButton();
        btnExcluirV = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtOrigem = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        cbFiltro = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ANAC - Organização da Malha Aérea");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.setToolTipText("");

        jPanel3.setLayout(new java.awt.BorderLayout());

        btnProcurarA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnProcurarA.setText("Procurar");
        jPanel5.add(btnProcurarA);

        btnIncluirA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnIncluirA.setText("Incluir");
        jPanel5.add(btnIncluirA);

        btnAlterarA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAlterarA.setText("Alterar");
        jPanel5.add(btnAlterarA);

        btnExcluirA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnExcluirA.setText("Excluir");
        jPanel5.add(btnExcluirA);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel6.setLayout(new java.awt.GridLayout(2, 2));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText(" Código");
        jPanel6.add(jLabel2);

        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel6.add(txtCodigo);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText(" Cidade");
        jPanel6.add(jLabel3);

        txtCidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel6.add(txtCidade);

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Manutenção de Aeroportos", jPanel3);

        jPanel2.setLayout(new java.awt.BorderLayout());

        btnProcurarV.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnProcurarV.setText("Procurar");
        jPanel7.add(btnProcurarV);

        btnIncluirV.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnIncluirV.setText("Incluir");
        jPanel7.add(btnIncluirV);

        btnAlterarV.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAlterarV.setText("Alterar");
        jPanel7.add(btnAlterarV);

        btnExcluirV.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnExcluirV.setText("Excluir");
        jPanel7.add(btnExcluirV);

        jPanel2.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jPanel8.setLayout(new java.awt.GridLayout(3, 2));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText(" Número");
        jPanel8.add(jLabel4);

        txtNumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel8.add(txtNumero);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText(" Aeroporto de Origem");
        jPanel8.add(jLabel5);

        txtOrigem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel8.add(txtOrigem);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText(" Aeroporto de Destino");
        jPanel8.add(jLabel6);

        txtDestino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel8.add(txtDestino);

        jPanel2.add(jPanel8, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Manutenção de Voos", jPanel2);

        jPanel4.setLayout(new java.awt.BorderLayout());

        cbFiltro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Número1", "Número2", "Número3" }));
        jPanel9.add(cbFiltro);

        jPanel4.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel10.setLayout(new java.awt.BorderLayout());

        tblLista.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Número", "Cidade de Destino"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLista);

        jPanel10.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel10, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Listagem", jPanel4);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarA;
    private javax.swing.JButton btnAlterarV;
    private javax.swing.JButton btnExcluirA;
    private javax.swing.JButton btnExcluirV;
    private javax.swing.JButton btnIncluirA;
    private javax.swing.JButton btnIncluirV;
    private javax.swing.JButton btnProcurarA;
    private javax.swing.JButton btnProcurarV;
    private javax.swing.JComboBox<String> cbFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblLista;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtOrigem;
    // End of variables declaration//GEN-END:variables
}
